version: "2"

issues:
  max-same-issues: 50

formatters:
  enable:
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - bodyclose
    - noctx
    - unused

  settings:
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true

    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1016
        - -QF1008

  exclusions:
    warn-unused: true
    rules:
      - path: '_test\.go'
        linters:
          - bodyclose
          - gosec
          - noctx
